using GNB.Api.App.Business;
using GNB.Api.App.Models;
using GNB.Api.App.Services;
using GNB.Api.App.Utilities;
using GNB.Api.App.ViewModels;
using Moq;
using NUnit.Framework;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GNB.Api.Tests.Business
{
    [TestFixture]
    internal class TransactionBusinessTest
    {
        private Mock<ITransactionService<TransactionModel>> transactionService;
        private Mock<ICurrencyConverter> currencyConverter;
        private TransactionBusiness transactionBusiness;


        [SetUp]
        public void SetUp()
        {
            transactionService = new Mock<ITransactionService<TransactionModel>>();
            currencyConverter = new Mock<ICurrencyConverter>();
            transactionBusiness = new TransactionBusiness(transactionService.Object, currencyConverter.Object);
        }

        [TestCaseSource(typeof(TransactionBusinessTest), "SomeTestsCases")]
        public async Task GetAllTransactionsWithNewCurrency(IEnumerable<TransactionModel> models)
        {
            transactionService.Setup(opt => opt.TryGetTransactions()).ReturnsAsync(models);

            IEnumerable<TransactionViewModel> result = await transactionBusiness.GetAllTransactions(new TransactionViewModel { CurrencyConverted = "EUR" });

            var changeCurrencyConverted = result.All(x => x.CurrencyConverted == "EUR");
            Assert.IsTrue(changeCurrencyConverted);
        }

        private static IEnumerable<TestCaseData> SomeTestsCases {
            get {
                yield return new TestCaseData
                (
                    new List<TransactionModel>
                        {
                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },                            new TransactionModel { Sku = "T2006", Amount = 7.36m, Currency = "USD" },
                            new TransactionModel { Sku = "T2006", Amount = 7.63m, Currency = "EUR" },
                        }
                ).SetName("WithOutConversion");
            }
        }
    }
}
